# Changes here will be overwritten by Copier.
_commit: 1.4.4
_src_path: gh:mkdocstrings/handler-template
author_email: jlewand2@elka.pw.edu.pl
author_fullname: jan lewandowski, jakub kosla, krzysztof sokol
author_username: jasiollo
copyright_date: '2025'
copyright_holder: jan lewandowski, jakub kosla, krzysztof sokol
copyright_holder_email: jlewand2@elka.pw.edu.pl
copyright_license: ISC
insiders: false
language: go
project_description: A Go handler for mkdocstrings.
project_name: mkdocstrings-go
python_package_distribution_name: mkdocstrings-go
python_package_import_name: go
repository_name: mkdocstrings-go
repository_namespace: jasiollo
repository_provider: github.com

